### ISSUE TITLE
Fails on files with Windows line endings (i.e. CRLF line endings)

### ISSUE THREAD

**Issue by eitland** [falkreon/Jankson#56] opened 2021-06-16 14:17 UTC
Whenever I try to read any file real life file that uses Windows style file endings it fails. Changing the line endings to Unix style solves the problem.

Let me know if I should throw together a test case, I have some files that can be easily stripped from data and reused as test files and I'll be happy to provide it if it simplifies anything.

**Comment by falkreon** [comment] 2021-06-19 14:55
That's interesting considering we're on a Reader these days (which should handle platform line endings for us) and newlines are more or less non-semantic. Fails how specifically?

**Comment by eitland** [comment] 2021-06-21 14:01
This is the exact message:

> blue.endless.jankson.api.SyntaxError: Found unexpected character '>' while looking for the colon (':') between a key and a value in an object

I've also realized that CRLF line endings seems to be necessary to trigger this but not enough, i.e.:
- not all files with CRLF line endings will fail
- but if I change a failing file to plain *nix file endings the problem disappears

I'll create a test case then. Hopefully after work today.

**Comment by LoganDark** [comment] 2022-03-30 20:42
Might be a BOM (Byte Order Marker)

**Comment by falkreon** [comment] 2023-03-15 15:27
Sorry for the delay!

Can't reproduce any problems with CRLF newlines, but I suspect that the problem is related to trailing whitespace (dos-style text editors *always* introduce a trailing newline). The fix for #64 should also fix this one, and will be included in the 1.2.2 release.

I've also introduced a regression test for CRLF bugs, so just in case they ever crash the parser in the future I'll know before release.

**Closed by falkreon** 2023-03-15 15:27 UTC
