### ISSUE TITLE
Option to preserve duplicate keys

### ISSUE THREAD

**Issue by Barteks2x** [falkreon/Jankson#13] opened 2019-09-03 08:06 UTC
This is a big big and potentially complicated feature request, so I'm not sure if it's going to be possible.

As explained in #11, some of my user's existing json files contain comments in the form
```json
"comment": "string",
"comment": "more text"
"comment": ~
"comment": "more text"
```
Which contains duplicate keys. I would like to be able to read and output json with those "comments" preserved. Currently with gson I just avoid writing that file back if possible, but in cases I can't avoid it, I do overwrite the user's file with those "comments" removed (and currently working on code to handle it anyway). i would like to be able to keep them as is, which doesn't appear to be possible here.

**Comment by falkreon** [comment] 2019-09-03 17:09
You're right, that's a thorny issue. I'd like to preserve the Map interface through java, but that may cause a cascade of unusual or unintended behaviors such as a get() returning the first instance of that key, but remove removing all of them. This kind of feature has to be approached really carefully.

**Comment by falkreon** [comment] 2021-05-23 14:59
Closing for now and kicking the ball over to Discussions until we have a concrete plan

**Closed by falkreon** 2021-05-23 14:59 UTC
Labels: Big Ol Can o' Worms, enhancement
